### ISSUE TITLE
Lack of theme?

### ISSUE THREAD

**Issue by Kyza** [zytexz/your-mom#3]
Where's the theme?

Also, [click this](https://www.youtube.com/watch?v=HQFxCxfhNUI).

**Comment by Overimagine1** [comment]
ok but like how i use ebter dicord

**Comment by Overimagine1** [comment]
@Kyza how i use idscord beter help

**Comment by Kyza** [comment]
> @Kyza how i use idscord beter help

[BetterDiscord website.](https://betterdiscord.app/)

**Comment by Kyza** [comment]
No problem.

**Comment by Kyza** [comment]
BetterDiscord.
